### ISSUE TITLE
Error in map argument

### ISSUE THREAD

**Issue by eeeXun** [Freed-Wu/tree-sitter-zathurarc#3]
```
map u scroll half-up
```
In above map, it should produce the syntax tree like

```
(map_directive (command) (key) (function) (argument))
```

But it seems that the argument in map do not consider the minus sign. The output is

```
(map_directive (command) (key) (function) (argument))
(ERROR)
```

**Comment by Freed-Wu** [comment]
I forget `half-up` can contains `-`.

**Comment by eeeXun** [comment]
Hi, thx for the fix. But this doesn't work for [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter). Did you forget to update the file in `src` directory?

**Comment by Freed-Wu** [comment]
Aha, I forget it. My memory has never be good :cry: Thanks for your noting!
